### ISSUE TITLE
Product fonts moar space plz

### ISSUE THREAD

**Issue by olizilla** [tableflip/lois#1]
Can has this pls...
![screenshot 2015-04-08 20 02 36](https://cloud.githubusercontent.com/assets/58871/7053046/54c036ac-de2a-11e4-8fca-1440ec5f8d9a.png)

via css changes like:

``` css
letter-spacing: 1px;
line-height: 1.4;
font-size: 1.5rem;
```

**Comment by richsilv** [comment]
Done.
